name: "Standard Discovery"
description: "Find out what to build & run in a Standard project."
author: "The Standard Authors"

outputs:
  hits:
    description: "JSON object containing CI actions to run."
    value: ${{ steps.eval.outputs.json }}

runs:
  using: "composite"
  steps:

    - if: contains( runner.os, 'macos')
      name: Install compatbile bash 5+
      shell: bash
      run: |
        nix profile install nixpkgs/nixpkgs-22.11-darwin#bash

    - name: Discover
      id: eval
      env:
        EVALSTORE_EXPORT: ${{ runner.temp }}/eval-store
        OWNER_AND_REPO: ${{ github.repository }}
        SHA: ${{ github.sha }}
      run: ${{ github.action_path }}/eval.sh
      shell: bash

    - uses: actions/cache/save@v3
      id: cache
      with:
        path: ${{ runner.temp }}/eval-store
        key: drv-pack-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
