name: "Standard Discovery"
description: "Find out what to build & run in a Standard project."

inputs:
  github_pat:
    description: "GitHub token for accessing private repos."
    required: false
    default: ${{ github.token }}

outputs:
  hits:
    description: "List of CI actions to run."
    value: ${{ steps.eval.outputs.json }}

runs:
  using: "composite"
  steps:
    - name: Set Environment
      run: |
        delim=$RANDOM

        cat << $delim >> "$GITHUB_ENV"
        $delim
      shell: bash

    - name: Cache Nix Store
      id: cache-nix
      uses: divnix/nix-cache-action@v3.0.11-nix
      with:
        path: |
          /nix
          ~/.cache/nix
          ~root/.cache/nix
        key: discovery-${{ runner.os }}-${{ runner.arch }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          discovery-${{ runner.os }}-${{ runner.arch }}-${{ github.ref }}-
          discovery-${{ runner.os }}-${{ runner.arch }}-


    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          accept-flake-config = true
          trusted-users = runner
          access-tokens = github.com=${{ inputs.github_pat }}

    - name: Discover
      id: eval
      env:
        FLAKE: "github:${{ github.repository }}/${{ github.sha }}"
      run: |
        ${{ github.action_path }}/eval.sh
      shell: bash
