name: "Standard Discovery"
description: "Find out what to build & run in a Standard project."

inputs:
  github_pat:
    description: "GitHub token for accessing private repos."
    required: false
    default: ${{ github.token }}

outputs:
  hits:
    description: "JSON object containing CI actions to run."
    value: ${{ steps.eval.outputs.json }}
  nix_conf:
    description: "Nix configuration of the flake."
    value: ${{ steps.eval.outputs.nix_conf }}

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v21
      if: startsWith(runner.name, 'discovery') == false
      with:
        nix_conf: |
          experimental-features = nix-command flakes
          accept-flake-config = true
          trusted-users = runner
          access-tokens = github.com=${{ inputs.github_pat }}

    - name: Cache Nix Store
      id: cache-nix
      if: startsWith(runner.name, 'discovery') == false
      uses: divnix/nix-cache-action@v3.0.11-nix
      with:
        path: |
          /nix
          ~/.cache/nix
          ~root/.cache/nix
        key: discovery-${{ runner.os }}-${{ runner.arch }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          discovery-${{ runner.os }}-${{ runner.arch }}-${{ github.ref }}-
          discovery-${{ runner.os }}-${{ runner.arch }}-

    - name: Discover
      id: eval
      env:
        TMPDIR: ${{ runner.temp }}
        FLAKE: "github:${{ github.repository }}/${{ github.sha }}"
        OS: ${{ runner.os }}
        SCRIPT: ${{ github.action_path }}/_eval.sh
      run: ${{ github.action_path }}/eval.sh
      shell: bash
