name: "Standard Discovery"
description: "Find out what to build & run in a Standard project."

inputs:
  # Authentication c/o Nix for additional private repositories
  nix_access_tokens:
    description: "Access Tokens to allow Nix to fetch private repositories."
    required: false
    default: github.com=${{ github.token }}
  use_cache:
    description: "Whether to use the cache"
    required: true
    default: "true"

outputs:
  hits:
    description: "JSON object containing CI actions to run."
    value: ${{ steps.eval.outputs.json }}

runs:
  using: "composite"
  steps:
    - name: Cache Nix Store
      id: cache-nix
      if: startsWith(runner.name, 'discovery') == false && inputs.use_cache != 'false'
      uses: divnix/nix-cache-action@v3.0.11-nix
      with:
        path: |
          /nix
          ~/.cache/nix
          ~root/.cache/nix
        key: discovery-${{ runner.os }}-${{ runner.arch }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          discovery-${{ runner.os }}-${{ runner.arch }}-${{ github.ref }}-
          discovery-${{ runner.os }}-${{ runner.arch }}-

    - name: Discover
      id: eval
      env:
        TMPDIR: ${{ runner.temp }}
        GH_TOKEN: ${{ github.token }}
        OWNER_AND_REPO: ${{ github.repository }}
        SHA: ${{ github.sha }}
        OS: ${{ runner.os }}
        SCRIPT: ${{ github.action_path }}/_eval.sh
      run: ${{ github.action_path }}/eval.sh
      shell: bash
