name: "Standard Action Runner"
description: "Build a target and run its action."
author: "The Standard Authors"

inputs:
  discovery_json:
    description: "JSON describing the action matrix, found in the discovery phase."
    required: true
    default: ${{ toJSON(matrix.target) }}
  # Discovery runner & builder host
  discovery_host:
    description: "SSH host URI for a persistent discovery runner."
    default: none
    required: false
  builder_host:
    description: "Nix store URI of a remote builder."
    default: auto
    required: false

runs:
  using: "composite"
  steps:
    - if: contains( runner.os, 'macos')
      name: Install compatbile bash 5+
      shell: bash
      run: |
        nix profile install nixpkgs/nixpkgs-22.11-darwin#bash

    - name: Parse Input
      shell: bash
      env:
        json: ${{ inputs.discovery_json }}
      run: |
        declare BUILDER action target cell block actionDrv
        eval "$(jq -r '@sh "action=\(.action) target=\(.name) cell=\(.cell) block=\(.block) actionDrv=\(.actionDrv)"' <<< "$json" )"
        echo "BUILDER=${{ inputs.builder_host }}" >> $GITHUB_ENV
        echo "cell=$cell" >> $GITHUB_ENV
        echo "block=$block" >> $GITHUB_ENV
        echo "target=$target" >> $GITHUB_ENV
        echo "action=$action" >> $GITHUB_ENV
        echo "actionDrv=$actionDrv" >> $GITHUB_ENV
        echo "actionDrvBasename=$(basename $actionDrv)" >> $GITHUB_ENV

    - uses: actions/cache/restore@v3
      id: cache
      with:
        path: ${{ runner.temp }}/eval-store
        key: drv-pack-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
        fail-on-cache-miss: true

    - name: Execute on ${{ env.target }}
      id: build
      run: ${{ github.action_path }}/execute.sh
      shell: bash
      env:
        EVALSTORE_IMPORT: ${{ runner.temp }}/eval-store
        # prj-spec <https://github.com/numtide/prj-spec>
        PRJ_ROOT: ${{ github.workspace }}
        PRJ_DATA_HOME: ${{ runner.temp }}/.data
        PRJ_CACHE_HOME: ${{ runner.temp }}/.cache
        PRJ_CONFIG_HOME: ${{ runner.temp }}/.config
        PRJ_RUNTIME_DIR: ${{ runner.temp }}/.run
        PRJ_PATH: ${{ runner.temp }}/.bin
