name: "Sandard Action Secrets"
description: "Setup common Nix secrets."

inputs:
  key_path:
    description: "The path to place the Nix secret key."
    required: false
    default: "${{ runner.temp }}/.nix-key"
  nix_key:
    description: "Secret key used for Nix package signing."
    required: false
  s3_key:
    description: "Key to upload to S3 Buckets with Nix."
    required: false
  s3_id:
    description: "ID to upload to S3 Buckets with Nix."
    required: false
  nix_ssh_key:
    description: "SSH private key to send builds to a remote Nix builder."
    default: none
    required: false
  ssh_known_hosts:
    description: "SSH known host keys for Nix builders"
    default: none
    required: false

runs:
  using: "composite"
  steps:
    - name: Set Environment
      run: |
        delim=$RANDOM

        cat << $delim >> "$GITHUB_ENV"
        SSH_AUTH_SOCK=${{ runner.temp }}/ssh_agent.sock
        NIX_KEY_PATH=${{ inputs.key_path }}
        $delim
      shell: bash

    - name: Emplace Secrets
      if: inputs.nix_key != '' || inputs.s3_id != '' || inputs.s3_key != ''
      run: ${{ github.action_path }}/secrets.sh
      shell: bash
      env:
        NIX_SECRET_KEY: ${{ inputs.nix_key }}
        AWS_ACCESS_KEY_ID: ${{ inputs.s3_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.s3_key }}

    - name: Setup SSH Keys
      if: inputs.nix_ssh_key != 'none'
      run: |
        ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
        ssh-add - <<< "${{ inputs.nix_ssh_key }}"
      shell: bash

    - name: Setup SSH Known Hosts
      if: inputs.nix_ssh_key != 'none' && inputs.ssh_known_hosts != 'none'
      run: |
        sudo sh -c 'echo "${{ inputs.ssh_known_hosts }}" >> /etc/ssh/ssh_known_hosts'
        sudo chmod 0644 /etc/ssh/ssh_known_hosts
      shell: bash
